<?php if ($this->isTagalysEnabled()): ?>
    <?php
        $currency = $this->getCurrentCurrency();
        $apiCredentials = $this->apiCredentials();
    ?>
    <script>
        require(['jquery', 'jquery/ui'], function($){ 
            try {
                $(document).on('tagalys:ready', function() {
                    $.fn.tagalys_search_suggestions.search_link = function( q, qf, qin ) {
                        var tagalys_search_base_url = "<?php echo $this->getTsearchUrl(); ?>?q=";
                        if (typeof(qf) == 'undefined' || $.isEmptyObject(qf)) {
                            return (tagalys_search_base_url + encodeURIComponent(q));
                        } else {
                            str = Object.keys(qf).map(function(key){ 
                                return  encodeURIComponent(key) + "-"+ encodeURIComponent(qf[key]); 
                            }).join('~');
                            qf_param = encodeURIComponent("qf") + '=' + str;

                            return tagalys_search_base_url.concat(encodeURIComponent(q) +"&"+qf_param);
                        }
                    };
                    $.fn.tagalys_search_suggestions.popular_searches  = function() {
                        <?php
                            try {
                                $popularSearches = $this->getTagalysConfig('store:' . $this->getCurrentStoreId() . ':popular_searches');
                                if ($popularSearches) {
                                    echo 'return ' . $popularSearches . ';';
                                } else {
                                    echo 'return [];';
                                }
                            } catch (Exception $e) {
                                echo 'return [];';
                            }
                        ?>
                    };
                    $('<?php echo $this->getTagalysConfig('search_box_selector') ?>').tagalys_search_suggestions({
                        currency: {
                            label: "<?php echo $currency['label']; ?>",
                            exchange_rate: "<?php echo  $currency['exchange_rate']; ?>",
                            fractional_digits:"<?php echo  $currency['fractional_digits']; ?>"
                        },
                        track: 'asynchronous',
                        align_to_parent: '<?php echo $this->getTagalysConfig('suggestions_align_to_parent_selector') ?>'
                    });
                });
            }
            catch(err) {
                
            }
        });
    </script>
<?php endif; ?>